[package]
name = "streamer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "streamer"
path = "src/main.rs"

[dependencies]
qobuz-api = { path = "kobuzapi" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "6"
reqwest = { version = "0.13", features = ["blocking"] }
tokio = { version = "1", features = ["rt"] }
rusqlite = { version = "0.31", features = ["bundled"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1"
