#pragma once
// Curve + MSDF font pipeline, shared by every entry point that needs to draw
// the GUI's screens (the interactive gui_main.cc loop and the headless
// tools/capture/main.cc snapshot tool) — factored out so it has external
// linkage instead of living in gui_main.cc's anonymous namespace.

#include "font.hh"
#include "msdf.hh"

#include <string>

class AssetReader;
class Renderer;

extern Font     g_font;
extern bool     g_font_ok;
extern MsdfFont g_msdf;
extern bool     g_msdf_ok;

// Loads the curve font + generates/loads the MSDF atlas (cached at `cache`)
// from `assets`. CPU-side only — no Renderer/GPU involved yet.
void init_fonts(AssetReader& assets, const std::string& cache);

// Uploads the MSDF atlas generated by init_fonts() into `r`'s GPU textures.
// Reloads the atlas pixels from `cache` first, so this is safe (and
// intended) to call once per Renderer — e.g. once for the live windowed
// Renderer and again for a separate headless one.
void upload_msdf(Renderer& r, const std::string& cache);

// Bakes glyphs for any codepoint in `utf8` that NewCM10 doesn't cover (CJK,
// Hangul, …) from the bundled fallback fonts, tried in order, into the
// shared MSDF atlas — see MsdfFont::bakeCodepoints(). Saves `cache` and
// returns true if it baked anything new, in which case the caller must
// re-run upload_msdf() to push the grown atlas to the GPU (see
// Renderer::initMsdf's re-entrant-call note in renderer.cc).
bool ensure_glyphs(AssetReader& assets, const std::string& cache, const std::string& utf8);
